### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jluebeck** [jluebeck/FaNDOM#1]
- [x] Implement XMAP output
- [x] Add a `-h` option to print FaNDOM args and description
- [x] Rename `threshold` argument to be more descriptive
- [x] Re-enable SV mode from unmerged codebase
- [x] Add fasta to OM reference generation script
- [ ] Port the E-value calculation from SegAligner to FANDOM.
